[build]
  base = "reenam-hotel"
  command = "npm run build"
  publish = "dist/reenam-hotel/browser"

# Single Page App redirect for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
